// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("source/Main.hx:8:","hi");
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
