// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("source/Main.hx:7:","Hello from Haxe!");
	genem_AudioPMP.playsound("assets/sounds/startup.wav");
	window.document.body.style.backgroundColor = "#000000";
};
var genem_AudioPMP = function() { };
genem_AudioPMP.playsound = function(url) {
	var sound = new Audio(url);
	sound.play();
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
